// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Planrbot.Server.Data;

#nullable disable

namespace Planrbot.Server.Migrations
{
	[DbContext(typeof(MainDbContext))]
	[Migration("20230228061130_Initial")]
	partial class Initial
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("Planrbot.Models.ToDoItem", b =>
			{
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("uniqueidentifier");

				b.Property<DateTime>("Date")
					.HasColumnType("datetime2");

				b.Property<string>("Description")
					.IsRequired()
					.HasMaxLength(100)
					.HasColumnType("nvarchar(100)");

				b.Property<bool>("IsComplete")
					.HasColumnType("bit");

				b.HasKey("Id");

				b.HasIndex("Id")
					.IsUnique();

				b.ToTable("ToDoItems");
			});
#pragma warning restore 612, 618
		}
	}
}
