global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using Moq.AutoMock;
global using Planrbot.Models;
global using Planrbot.Server.Data;
global using Planrbot.Web.Server.Controllers;
global using Xunit;
